name: ai-archive-server

services:

  queue-manager:
    build:
      context: .
      dockerfile: docker/queue-manager/Dockerfile

    container_name: ai-archive-queue-manager

    restart: unless-stopped

    ports:
      - "8080:8080"

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
      - ./registry/data:/app/registry/data


  download-worker:
    build:
      context: .
      dockerfile: docker/download-worker/Dockerfile

    container_name: ai-archive-download-worker

    restart: unless-stopped

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
      - ./registry/data:/app/registry/data